channels:
- bioconda
- conda-forge
dependencies:
- samtools=1.9
- salmon=1.2.0
- star=2.7.3a
- fastqc=0.11.8
- multiqc=1.7
- trim-galore=0.6.4
- cutadapt=2.6
- bedtools=2.29.0
- ucsc-bedgraphtobigwig=377
- pandoc
