channels:
- bioconda
- conda-forge
dependencies:
- samtools=1.11
- salmon=1.4.0
- star=2.7.7a
- fastqc=0.11.9
- multiqc=1.9
- trim-galore=0.6.6
- cutadapt=3.2
- bedtools=2.30.0
- ucsc-bedgraphtobigwig=377
- pandoc=2.11
- tbb=2020.2
