channels:
- r
- bioconda
- conda-forge
dependencies:
- samtools=1.9
- salmon=0.10.2
- star=2.6.0c
- fastqc=0.11.7
- multiqc=1.6a0
- trim-galore=0.5.0
- cutadapt=1.16
- bedtools=2.27.1
- ucsc-bedgraphtobigwig=366
- r=3.5.1
